// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJ8f2KOwhb92hmEooXQ4zbjoa3Uni9wU',
    appId: '1:743494414965:web:02b2e357830e5ffd4dbe3c',
    messagingSenderId: '743494414965',
    projectId: 'flutter-cars-8733e',
    authDomain: 'flutter-cars-8733e.firebaseapp.com',
    storageBucket: 'flutter-cars-8733e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKTBS6OrnneCMZiZd0GA8MpY4BrEKR_ss',
    appId: '1:743494414965:android:7434126f06c050c24dbe3c',
    messagingSenderId: '743494414965',
    projectId: 'flutter-cars-8733e',
    storageBucket: 'flutter-cars-8733e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc4Z6IAgTF1nUgiNoZat0M-oxZ2P0gRqk',
    appId: '1:743494414965:ios:9b8ad1a4543874964dbe3c',
    messagingSenderId: '743494414965',
    projectId: 'flutter-cars-8733e',
    storageBucket: 'flutter-cars-8733e.appspot.com',
    iosBundleId: 'com.example.flutterCars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc4Z6IAgTF1nUgiNoZat0M-oxZ2P0gRqk',
    appId: '1:743494414965:ios:9b8ad1a4543874964dbe3c',
    messagingSenderId: '743494414965',
    projectId: 'flutter-cars-8733e',
    storageBucket: 'flutter-cars-8733e.appspot.com',
    iosBundleId: 'com.example.flutterCars',
  );
}
